// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTgDntQbbgU-gW1AF4f9jNvTGOCelhEow',
    appId: '1:1055382369865:web:5b39a4e3109b5011b2f198',
    messagingSenderId: '1055382369865',
    projectId: 'flutterfire-f7f57',
    authDomain: 'flutterfire-f7f57.firebaseapp.com',
    storageBucket: 'flutterfire-f7f57.appspot.com',
    measurementId: 'G-9T88HGCHEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmUGUWSyay7gxURE0fblPtOBuSsrwPt_Y',
    appId: '1:1055382369865:android:539101e5ac2fb2fab2f198',
    messagingSenderId: '1055382369865',
    projectId: 'flutterfire-f7f57',
    storageBucket: 'flutterfire-f7f57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAXC7jbqZBN1Fpa8fRoeZzah75HwTxxQs',
    appId: '1:1055382369865:ios:117c704270681d36b2f198',
    messagingSenderId: '1055382369865',
    projectId: 'flutterfire-f7f57',
    storageBucket: 'flutterfire-f7f57.appspot.com',
    iosClientId: '1055382369865-esq2tpb1p6a1jded7rgilc4800vvmq9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfireTrial0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAXC7jbqZBN1Fpa8fRoeZzah75HwTxxQs',
    appId: '1:1055382369865:ios:117c704270681d36b2f198',
    messagingSenderId: '1055382369865',
    projectId: 'flutterfire-f7f57',
    storageBucket: 'flutterfire-f7f57.appspot.com',
    iosClientId: '1055382369865-esq2tpb1p6a1jded7rgilc4800vvmq9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfireTrial0',
  );
}
